[{oxhasrights ident="SHOWARTICLEPRICE"}]
    [{if $oDetailsProduct->getPrice()}]
        [{if $oDetailsProduct->loadAmountPriceInfo()}]
            [{include file="page/details/inc/priceinfo.tpl"}]
        [{/if}]
    [{/if}]
[{/oxhasrights}]
