tpl: 'application/views/roxid/tpl'
module: 'modules/roxid/'
tmp: 'out/roxid/build/.tmp'
bower: 'out/roxid/bower_components'
src:
  js: 'out/roxid/src/js'
  css: 'out/roxid/src/css'
  favicons: 'out/roxid/src/favicons'
dest:
  js: 'out/roxid/build/js'
  css: 'out/roxid/build/css'
  fonts: 'out/roxid/build/fonts'
  favicons: 'out/roxid/build/favicons'
  assets: 'out/roxid/build/assets'
