[{if $oxcmp_user->oxuser__oxcompany->value }] [{ $oxcmp_user->oxuser__oxcompany->value }]<br> [{/if}]
[{if $oxcmp_user->oxuser__oxaddinfo->value }] [{ $oxcmp_user->oxuser__oxaddinfo->value }]<br>[{/if}]
[{if $oxcmp_user->oxuser__oxustid->value }] [{ oxmultilang ident="VAT_ID_NUMBER" suffix="COLON" }] [{ $oxcmp_user->oxuser__oxustid->value }]<br> [{/if}]
[{if $oxcmp_user->oxuser__oxsal->value || $oxcmp_user->oxuser__oxfname->value || $oxcmp_user->oxuser__oxlname->value}][{ $oxcmp_user->oxuser__oxsal->value|oxmultilangsal}]&nbsp;[{ $oxcmp_user->oxuser__oxfname->value }]&nbsp;[{ $oxcmp_user->oxuser__oxlname->value }]<br>[{/if}]
[{if $oxcmp_user->oxuser__oxstreet->value || $oxcmp_user->oxuser__oxstreetnr->value}][{ $oxcmp_user->oxuser__oxstreet->value }]&nbsp;[{ $oxcmp_user->oxuser__oxstreetnr->value }]<br>[{/if}]
[{if $oxcmp_user->oxuser__oxstateid->value}][{$oxcmp_user->getStateTitle()}] [{/if}]
[{if $oxcmp_user->oxuser__oxzip->value || $oxcmp_user->oxuser__oxcity->value}][{ $oxcmp_user->oxuser__oxzip->value }]&nbsp;[{ $oxcmp_user->oxuser__oxcity->value }]<br>[{/if}]
[{if $oxcmp_user->oxuser__oxcountry->value }][{ $oxcmp_user->oxuser__oxcountry->value }][{/if}]

[{if $oxcmp_user->oxuser__oxusername->value || ($oViewConf->getViewThemeParam('blShowFax') && $oxcmp_user->oxuser__oxfon->value) || ($oViewConf->getViewThemeParam('blShowFax') && $oxcmp_user->oxuser__oxfax->value) || ($oViewConf->getViewThemeParam('blShowMobFon') && $oxcmp_user->oxuser__oxmobfon->value) || ($oViewConf->getViewThemeParam('blShowPrivFon') && $oxcmp_user->oxuser__oxprivfon->value)}]<br><br>[{/if}]
[{if $oxcmp_user->oxuser__oxusername->value}][{ oxmultilang ident="EMAIL" suffix="COLON" }]&nbsp;[{ $oxcmp_user->oxuser__oxusername->value }]<br>[{/if}]
[{if $oViewConf->getViewThemeParam('blShowFon')}]
    [{if $oxcmp_user->oxuser__oxfon->value }] [{ oxmultilang ident="PHONE" suffix="COLON" }] [{ $oxcmp_user->oxuser__oxfon->value }]<br>[{/if}]
[{/if}]
[{if $oViewConf->getViewThemeParam('blShowFax')}]
    [{if $oxcmp_user->oxuser__oxfax->value }] [{ oxmultilang ident="FAX" suffix="COLON" }] [{ $oxcmp_user->oxuser__oxfax->value }]<br>[{/if}]
[{/if}]
[{if $oViewConf->getViewThemeParam('blShowMobFon')}]
    [{if $oxcmp_user->oxuser__oxmobfon->value }] [{ oxmultilang ident="CELLUAR_PHONE" suffix="COLON" }] [{ $oxcmp_user->oxuser__oxmobfon->value }]<br>[{/if}]
[{/if}]
[{if $oViewConf->getViewThemeParam('blShowPrivFon')}]
    [{if $oxcmp_user->oxuser__oxprivfon->value }] [{ oxmultilang ident="PERSONAL_PHONE" suffix="COLON" }] [{ $oxcmp_user->oxuser__oxprivfon->value }][{/if}]
[{/if}]
<br>
